---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-Find-Simple
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Encode: 0
  URI::Find: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/neilbowers/URI-Find-Simple.git
version: 1.04
